name: Manual Build Release APK and APP Bundle

on:     
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  buildBundle:
    name: Build APP Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.3'
      - run: flutter pub get
      - run: flutter build appbundle
      - name: Push APP Bundle to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab"          
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master
          tag: ${{github.event.inputs.version}}
  buildApk:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.3'
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: Push APP Bundle to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"          
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master
          tag: ${{github.event.inputs.version}}
      
