name: Trigger Build Release APK and APP Bundle

on:     
  pull_request:
    branches: 
      - master
    tags: 
      - 'v*.*.*'
jobs:
  build:
    name: Build APP Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.3'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi   
      - run: flutter build appbundle
      - name: Push APP Bundle and APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/app-release.aab,build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
