name: Manual Build Release IOS

on:     
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  build:
    name: Build IOS 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.3'
      - run: flutter pub get      
      - run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace YOUR_WORKSPACE.xcworkspace -scheme YOUR_SCHEME -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/MY_APP.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/MY_APP.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build -allowProvisioningUpdates
          rm -fr Runner.xcarchive
          cd ..
          ls
