name: Manual Build Release IOS

on:     
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  build:
    name: Build IOS 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.3'
      - run: flutter pub get      
      - run: |
          flutter build ios --release --no-codesign   
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Release App IOS
        uses: ncipollo/release-action@v1
        with:
          tag: ${{github.event.inputs.version}}
          name: Release ${{github.event.inputs.version}}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/ios/iphoneos/app.ipa"
